services:
  server:
    build:
      context: .
      target: dev
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: example
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./.env:/app/.env
      - ./app:/app/app
      - ./components:/app/components
      - ./utils:/app/utils
      - ./api-server.js:/app/api-server.js
      - ./tests:/app/tests
    # depends_on:
    #   db:
    #     condition: service_healthy
    # secrets:
    #   - db-password
    
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt
  test:
    build:
      context: .
      target: test-suite
    command: "-f /dev/null"
    entrypoint: /usr/bin/tail
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: example
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./.env:/app/.env
      - ./app:/app/app
      - ./components:/app/components
      - ./utils:/app/utils
      - ./api-server.js:/app/api-server.js
      - ./tests:/app/tests
  e2e-chrome:
    image: "cypress/included:12.12.0"
    # container_name: cypress
    # "cypress/included" images have entrypoint set to globally installed cypress
    # so the command can simply add any arguments
    command: "--browser chrome"
    volumes:
      - ./cypress:/cypress
      - ./cypress.config.js:/cypress.config.js